// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGO71CYPggLLKP_4dJzEwN4ge0DSu04g4',
    appId: '1:584743494623:web:3559d322461f54293e1a6a',
    messagingSenderId: '584743494623',
    projectId: 'prueba-46e03',
    authDomain: 'prueba-46e03.firebaseapp.com',
    databaseURL: 'https://prueba-46e03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prueba-46e03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9EJFOzP4WQ3FAufvIZZCQ-1Cc-FrhNJU',
    appId: '1:584743494623:android:e105a0b66d8778b83e1a6a',
    messagingSenderId: '584743494623',
    projectId: 'prueba-46e03',
    databaseURL: 'https://prueba-46e03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prueba-46e03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTydAJbmSD6ZdnTv-jc-mSGm-wuJA6x5g',
    appId: '1:584743494623:ios:c70ebb3681b96db33e1a6a',
    messagingSenderId: '584743494623',
    projectId: 'prueba-46e03',
    databaseURL: 'https://prueba-46e03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prueba-46e03.appspot.com',
    iosBundleId: 'com.example.adoptaAmigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTydAJbmSD6ZdnTv-jc-mSGm-wuJA6x5g',
    appId: '1:584743494623:ios:80b94a2ba49f36223e1a6a',
    messagingSenderId: '584743494623',
    projectId: 'prueba-46e03',
    databaseURL: 'https://prueba-46e03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prueba-46e03.appspot.com',
    iosBundleId: 'com.example.adoptaAmigo.RunnerTests',
  );
}
