// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm5amV6OJc8fkUeur9GCNa7ZfBbDOsr2s',
    appId: '1:695985571055:web:042d59428e17284482c71a',
    messagingSenderId: '695985571055',
    projectId: 'adoptamigo-ae1c2',
    authDomain: 'adoptamigo-ae1c2.firebaseapp.com',
    storageBucket: 'adoptamigo-ae1c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Wn2i2TEg6vxLeQwujTGVdxqtXD4ZZZQ',
    appId: '1:695985571055:android:ddd8c5126ac5eb1c82c71a',
    messagingSenderId: '695985571055',
    projectId: 'adoptamigo-ae1c2',
    storageBucket: 'adoptamigo-ae1c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNayXwoOZv8wqzMkDq7dz6NTnGH-4fl54',
    appId: '1:695985571055:ios:bb5794748d52a8b782c71a',
    messagingSenderId: '695985571055',
    projectId: 'adoptamigo-ae1c2',
    storageBucket: 'adoptamigo-ae1c2.appspot.com',
    iosBundleId: 'com.example.adoptaAmigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNayXwoOZv8wqzMkDq7dz6NTnGH-4fl54',
    appId: '1:695985571055:ios:bb5794748d52a8b782c71a',
    messagingSenderId: '695985571055',
    projectId: 'adoptamigo-ae1c2',
    storageBucket: 'adoptamigo-ae1c2.appspot.com',
    iosBundleId: 'com.example.adoptaAmigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm5amV6OJc8fkUeur9GCNa7ZfBbDOsr2s',
    appId: '1:695985571055:web:adeccc7695a4f74182c71a',
    messagingSenderId: '695985571055',
    projectId: 'adoptamigo-ae1c2',
    authDomain: 'adoptamigo-ae1c2.firebaseapp.com',
    storageBucket: 'adoptamigo-ae1c2.appspot.com',
  );

}